apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "Geonorge.ApiServices"
spec:
  type: "service"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
